version: '3.9'

services:
  playing-with-elk-api:
    container_name: api
    links:
      - playing-with-elk-db
    depends_on:
      - playing-with-elk-db
    environment:
      DB_HOST: db
    ports:
      - "8080:8080"
    volumes:
      - elk-gradle-cache:/home/gradle/.gradle
    build: .

  playing-with-elk-db:
    container_name: db
    image: postgres:13.4-alpine
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - elk-volume:/var/lib/postgresql/data
    env_file:
      - ../../postgres.dev.env

volumes:
  elk-volume:
  elk-gradle-cache:
